Algoritmo "DOIS NUMEROS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : PEDRO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : RUBENS FILIPE
// Data atual  : 21/04/2020
Var

A,B:INTEIRO


Inicio


ESCREVA("INFORME O PRIMEIRO NUMERO ")
LEIA(A)

ESCREVA("INFORME O SEGUNDO NUMERO ")
LEIA(B)

SE (A % B = 0) ENTAO
   ESCREVA("O NUMERO ", A, " É DIVISIVEL POR ", B)
SENAO
   ESCREVA("NÃO É DIVISIVEL")
FIMSE


Fimalgoritmo