Algoritmo "MOSTRA NUMERO QUE É MAIOR QUE 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : PEDRO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : RUBENS FILIPE FERREIRA PEREIRA
// Data atual  : 19/04/2020
Var

NUMERO: INTEIRO


Inicio

ESCREVA("DIGITE UM NUMERO: ")
LEIA(NUMERO)
SE NUMERO > 10 ENTAO
   ESCREVA(NUMERO, " ESTE NUMERO É MAIOR QUE 10!")
SENAO
   SE NUMERO <= 10 ENTAO
      ESCREVA(NUMERO)
   FIMSE
FIMSE



Fimalgoritmo