Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : PEDRO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : RUBENS FILIPE
// Data atual  : 26/03/2020
Var
NUMBER, A, RESULTADO:INTEIRO


Inicio

ESCREVA("DIGITE UM NUMERO PARA FAZERMOS A TABUADA: ")
LEIA(NUMBER)
PARA A DE 1 ATE 10 FACA
     RESULTADO <- NUMBER * A
     ESCREVAL(NUMBER, " X ", A, " = ", RESULTADO)
FIMPARA

Fimalgoritmo