Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : PEDRO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : RUBENS FILIPE
// Data atual  : 24/03/2020
Var
numA, numB, result: inteiro


Inicio

Escreva("Escreva o valor A ")
Leia(numA)
Escreva("Escreva o valor B ")
Leia(numB)
Escreva("O resultado de A + B é ")
result <- numA + numB
Escreva(result)

Fimalgoritmo