Algoritmo "TROCA DE VALORES"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : PEDRO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : RUBENS FILIPE
// Data atual  : 26/03/2020
Var
VALORA, VALORB, VALUEA, VALUEB: INTEIRO


Inicio

ESCREVA("ESCREVA O VALOR A: ")
LEIA(VALORA)
ESCREVA("ESCREVA O VALOR B: ")
LEIA(VALORB)

VALUEA <- VALORB
VALUEB <- VALORA

ESCREVAL("O VALOR A É: ", VALUEA)
ESCREVAL("O VALOR B É: ", VALUEB)

Fimalgoritmo